FROM python:3.7-slim
LABEL maintainer="Orchest B.V. https://www.orchest.io"

# Make sudo available for more granular user permissions
RUN apt-get update && apt-get install -y sudo

# Get all requirements in place.
COPY ./requirements.txt ./start_celery_workers.sh /orchest/services/orchest-api/
COPY ./lib/python /orchest/lib/python

# Set the `WORKDIR` so the editable installs in the `requirements.txt`
# can use relative paths.
WORKDIR /orchest/services/orchest-api/
RUN pip3 install -r requirements.txt

# Application files.
COPY ./app ./app

# This `WORKDIR` is required for the context of the application of the
# `start_celery_workers.sh` script.
WORKDIR /orchest/services/orchest-api/app/
ARG ORCHEST_VERSION
ENV ORCHEST_VERSION=${ORCHEST_VERSION}
CMD ["./../start_celery_workers.sh"]
