//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The orchest Authors.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerRegistrySpec) DeepCopyInto(out *DockerRegistrySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerRegistrySpec.
func (in *DockerRegistrySpec) DeepCopy() *DockerRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(DockerRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestCluster) DeepCopyInto(out *OrchestCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(OrchestClusterStatus)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestCluster.
func (in *OrchestCluster) DeepCopy() *OrchestCluster {
	if in == nil {
		return nil
	}
	out := new(OrchestCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrchestCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestClusterList) DeepCopyInto(out *OrchestClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*OrchestCluster, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(OrchestCluster)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestClusterList.
func (in *OrchestClusterList) DeepCopy() *OrchestClusterList {
	if in == nil {
		return nil
	}
	out := new(OrchestClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrchestClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestClusterSpec) DeepCopyInto(out *OrchestClusterSpec) {
	*out = *in
	if in.DefaultNodeSelector != nil {
		in, out := &in.DefaultNodeSelector, &out.DefaultNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Orchest.DeepCopyInto(&out.Orchest)
	in.Registry.DeepCopyInto(&out.Registry)
	in.Postgres.DeepCopyInto(&out.Postgres)
	in.RabbitMq.DeepCopyInto(&out.RabbitMq)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestClusterSpec.
func (in *OrchestClusterSpec) DeepCopy() *OrchestClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OrchestClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestClusterStatus) DeepCopyInto(out *OrchestClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestClusterStatus.
func (in *OrchestClusterStatus) DeepCopy() *OrchestClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OrchestClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestComponent) DeepCopyInto(out *OrchestComponent) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestComponent.
func (in *OrchestComponent) DeepCopy() *OrchestComponent {
	if in == nil {
		return nil
	}
	out := new(OrchestComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestResourcesSpec) DeepCopyInto(out *OrchestResourcesSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestResourcesSpec.
func (in *OrchestResourcesSpec) DeepCopy() *OrchestResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(OrchestResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrchestSpec) DeepCopyInto(out *OrchestSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Resources = in.Resources
	in.OrchestApi.DeepCopyInto(&out.OrchestApi)
	in.OrchestWebServer.DeepCopyInto(&out.OrchestWebServer)
	in.CeleryWorker.DeepCopyInto(&out.CeleryWorker)
	in.NodeAgent.DeepCopyInto(&out.NodeAgent)
	in.AuthServer.DeepCopyInto(&out.AuthServer)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrchestSpec.
func (in *OrchestSpec) DeepCopy() *OrchestSpec {
	if in == nil {
		return nil
	}
	out := new(OrchestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresSpec) DeepCopyInto(out *PostgresSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresSpec.
func (in *PostgresSpec) DeepCopy() *PostgresSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQSpec) DeepCopyInto(out *RabbitMQSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQSpec.
func (in *RabbitMQSpec) DeepCopy() *RabbitMQSpec {
	if in == nil {
		return nil
	}
	out := new(RabbitMQSpec)
	in.DeepCopyInto(out)
	return out
}
