{{/*
deployment
*/}}
---
{{ include "library.deployment" . }}
    spec:
      serviceAccountName: {{ template "library.metadata.name" . }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      containers:
      - name: orchest-controller
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ include "library.spec.image.pullPolicy" . }}
        ports:
        - containerPort: 80
        args:
        - --defaultVersion=$(VERSION)
        - --namespace=$(NAMESPACE)
        {{ if eq .Values.clusterLevelAddons.enableArgo true }}
        - --enable=argo-workflow
        {{ end }}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VERSION
            value: {{ .Values.image.tag }}
