/*
Copyright 2022 The orchest Authors.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// OrchestClusterListerExpansion allows custom methods to be added to
// OrchestClusterLister.
type OrchestClusterListerExpansion interface{}

// OrchestClusterNamespaceListerExpansion allows custom methods to be added to
// OrchestClusterNamespaceLister.
type OrchestClusterNamespaceListerExpansion interface{}

// OrchestComponentListerExpansion allows custom methods to be added to
// OrchestComponentLister.
type OrchestComponentListerExpansion interface{}

// OrchestComponentNamespaceListerExpansion allows custom methods to be added to
// OrchestComponentNamespaceLister.
type OrchestComponentNamespaceListerExpansion interface{}
