  apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: {{ include "library.cluster.ceph.filesystem.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
{{ toYaml .Values.cephFileSystems.spec | indent 2 }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "library.cluster.ceph.filesystem.storageclass" . }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ if default false .Values.cephFileSystems.storageClass.isDefault }}true{{ else }}false{{ end }}"
provisioner: {{ .Release.Namespace }}.cephfs.csi.ceph.com
parameters:
  fsName: {{ include "library.cluster.ceph.filesystem.name" . }}
  pool: {{ include "library.cluster.ceph.filesystem.name" . }}-data0
  clusterID: {{ .Release.Namespace }}
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/fstype: {{ .Values.cephFileSystems.storageClass.fstype }}
reclaimPolicy: {{ default "Delete" .Values.cephFileSystems.storageClass.reclaimPolicy }}
allowVolumeExpansion: {{ default "true" .Values.cephFileSystems.storageClass.allowVolumeExpansion }}
{{- if .Values.cephFileSystems.storageClass.mountOptions }}
mountOptions:
  {{- range .Values.cephFileSystems.storageClass.mountOptions }}
  - {{ . }}
  {{- end }} 
{{- end }}