apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: {{ include "library.cluster.ceph.blockpool.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
{{ toYaml .Values.cephBlockPools.spec | indent 2 }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "library.cluster.ceph.blockpool.storageclass" . }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ if default false .Values.cephBlockPools.storageClass.isDefault }}true{{ else }}false{{ end }}"
provisioner: {{ .Release.Namespace }}.rbd.csi.ceph.com
parameters:
  pool: {{ include "library.cluster.ceph.blockpool.name" . }}
  clusterID: {{ .Release.Namespace }}
  imageFormat: {{ .Values.cephBlockPools.storageClass.imageFormat | quote }}
  imageFeatures: {{ .Values.cephBlockPools.storageClass.imageFeatures }}
  # The secrets contain Ceph admin credentials. These are generated automatically by the operator
  # in the same namespace as the cluster.
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/fstype: {{ .Values.cephBlockPools.storageClass.fstype }}
reclaimPolicy: {{ default "Delete" .Values.cephBlockPools.storageClass.reclaimPolicy }}
allowVolumeExpansion: {{ default "true" .Values.cephBlockPools.storageClass.allowVolumeExpansion }}
{{- if .Values.cephBlockPools.storageClass.mountOptions }}
mountOptions:
  {{- range .Values.cephBlockPools.storageClass.mountOptions }}
  - {{ . }}
  {{- end }} 
{{- end }}
