"""empty message

Revision ID: bffbc3eef681
Revises: 7898eecfbe51
Create Date: 2021-03-06 22:09:53.679512

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bffbc3eef681"
down_revision = "7898eecfbe51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jupyter_builds",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("requested_time", sa.DateTime(), nullable=False),
        sa.Column("started_time", sa.DateTime(), nullable=True),
        sa.Column("finished_time", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=15), nullable=True),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_jupyter_builds")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("jupyter_builds")
    # ### end Alembic commands ###
