"""Add ix_type_job_uuid_pipeline_run_index to pipeline_runs

Revision ID: ef7f54441e8f
Revises: a25c8a60484c
Create Date: 2021-12-21 11:25:58.651201

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef7f54441e8f"
down_revision = "a25c8a60484c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_type_job_uuid_pipeline_run_index",
        "pipeline_runs",
        ["type", "job_uuid", "pipeline_run_index"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_type_job_uuid_pipeline_run_index", table_name="pipeline_runs")
    # ### end Alembic commands ###
