"""Add user_services to interactive_sessions

Revision ID: efadd665f3f1
Revises: bffbc3eef681
Create Date: 2021-06-01 12:32:52.030746

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "efadd665f3f1"
down_revision = "bffbc3eef681"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interactive_sessions",
        sa.Column(
            "user_services",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("interactive_sessions", "user_services")
    # ### end Alembic commands ###
