apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "library.cluster.registry.certificate" . }}
  namespace: {{ .Release.Namespace }}
spec:
  # Secret names are always required.
  secretName: {{ .Values.secret }}

  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - orchest

  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - {{ include "library.cluster.registry.dns" . }}
  uris:
    - {{ include "library.cluster.registry.uri" . }}
  # Issuer references are always required.
  issuerRef:
    name: {{ include "library.cluster.issuer.name" . }}
    kind: Issuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
