operatorNamespace: rook-ceph

cephBlockPools:
  name: ceph-blockpool
  # see https://github.com/rook/rook/blob/master/Documentation/ceph-pool-crd.md#spec for available configuration
  spec:
    failureDomain: osd
    replicated:
      size: 3
  storageClass:
    enabled: true
    name: ceph-block
    isDefault: true
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    mountOptions: []
    # RBD image format. Defaults to "2".
    imageFormat: "2"
    # RBD image features. Available for imageFormat: "2". CSI RBD currently supports only `layering` feature.
    imageFeatures: layering
    # Specify the filesystem type of the volume. If not specified, csi-provisioner
    # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
    # in hyperconverged settings where the volume is mounted on the same node as the osds.
    fstype: ext4

      