name: Publish SDK & CLI to PyPi

# Whenever Orchest is released, also publish the Orchest SDK.
on:
  release:
    types: [published]

jobs:
  upload-to-pypi:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Upload SDK
        run: |
          cd orchest-sdk/python
          python setup.py sdist
          twine upload dist/* --non-interactive --skip-existing

      - name: Upload CLI
        run: |
          cd orchest-cli
          python setup.py sdist
          twine upload dist/* --non-interactive --skip-existing
